version: "3"

services:
  web:
    build: .
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DB_USER=pokemon_eggs
      - DB_PASSWORD=udnvLYfb59
      - DB_URL=postgresql://pokemon_eggs:udnvLYfb59@localhost:5432/pokemon_eggs_db

volumes:
  postgres_data:
