"""create users table

Revision ID: 21516fd47572
Revises: 
Create Date: 2022-12-13 10:53:38.383100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21516fd47572'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.Column('type1', sa.String(length=50), nullable=False),
    sa.Column('type2', sa.String(length=50), nullable=True),
    sa.Column('evolution_id', sa.Integer(), nullable=True),
    sa.Column('evolution_lvl', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_pokemon',
    sa.Column('user.id', sa.Integer(), nullable=False),
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('time_hatched', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user.id', 'pokemon_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_pokemon')
    op.drop_table('users')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
