"""2 added baby column to pokemon table

Revision ID: 35190e702c79
Revises: 21516fd47572
Create Date: 2022-12-13 12:18:23.988256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35190e702c79'
down_revision = '21516fd47572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baby', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pokemon', schema=None) as batch_op:
        batch_op.drop_column('baby')

    # ### end Alembic commands ###
