"""3 added level column to user pokemon table

Revision ID: 8fbc56ea6bac
Revises: 35190e702c79
Create Date: 2022-12-13 12:47:17.873419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fbc56ea6bac'
down_revision = '35190e702c79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_pokemon', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
